# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
UniformRandom
"""


from ..utils.entrypoints import Component


def uniform_random(
        **params):
    """
    **Description**
        AutoML engine using uniform random sampling.

    """

    entrypoint_name = 'UniformRandom'
    settings = {}

    component = Component(
        name=entrypoint_name,
        settings=settings,
        kind='AutoMlEngine')
    return component
