# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
PavCalibrator
"""


from ..utils.entrypoints import Component


def pav_calibrator(
        **params):
    """
    **Description**
        None

    """

    entrypoint_name = 'PavCalibrator'
    settings = {}

    component = Component(
        name=entrypoint_name,
        settings=settings,
        kind='CalibratorTrainer')
    return component
