# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
TR
"""

import numbers

from ..utils.entrypoints import Component
from ..utils.utils import try_set


def tr(
        threshold=0.01,
        **params):
    """
    **Description**
        Stop if validation score exceeds threshold value.

    :param threshold: Tolerance threshold. (Non negative value)
        (settings).
    """

    entrypoint_name = 'TR'
    settings = {}

    if threshold is not None:
        settings['Threshold'] = try_set(
            obj=threshold,
            none_acceptable=True,
            is_of_type=numbers.Real, valid_range={'Min': 0.0})

    component = Component(
        name=entrypoint_name,
        settings=settings,
        kind='EarlyStoppingCriterion')
    return component
