# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
MultiWeightedAverage
"""


from ..utils.entrypoints import Component
from ..utils.utils import try_set


def multi_weighted_average(
        weightage_name='AccuracyMicroAvg',
        normalize=True,
        **params):
    """
    **Description**
        None

    :param weightage_name: The metric type to be used to find the
        weights for each model (settings).
    :param normalize: Whether to normalize the output of base models
        before combining them (settings).
    """

    entrypoint_name = 'MultiWeightedAverage'
    settings = {}

    if weightage_name is not None:
        settings['WeightageName'] = try_set(
            obj=weightage_name,
            none_acceptable=True,
            is_of_type=str,
            values=[
                'AccuracyMicroAvg',
                'AccuracyMacroAvg'])
    if normalize is not None:
        settings['Normalize'] = try_set(
            obj=normalize, none_acceptable=True, is_of_type=bool)

    component = Component(
        name=entrypoint_name,
        settings=settings,
        kind='EnsembleMulticlassOutputCombiner')
    return component
