# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
IterationLimited
"""

import numbers

from ..utils.entrypoints import Component
from ..utils.utils import try_set


def iteration_limited(
        final_history_length=0,
        **params):
    """
    **Description**
        Terminators a sweep based on total number of iterations.

    :param final_history_length: Total number of iterations.
        (settings).
    """

    entrypoint_name = 'IterationLimited'
    settings = {}

    if final_history_length is not None:
        settings['FinalHistoryLength'] = try_set(
            obj=final_history_length,
            none_acceptable=False,
            is_of_type=numbers.Real)

    component = Component(
        name=entrypoint_name,
        settings=settings,
        kind='SearchTerminator')
    return component
