# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
Data.PredictorModelArrayConverter
"""


from ..utils.entrypoints import EntryPoint
from ..utils.utils import try_set, unlist


def data_predictormodelarrayconverter(
        model,
        output_model,
        **params):
    """
    **Description**
        Create an array variable of PredictorModel

    :param model: The models (inputs).
    :param output_model: The model array (outputs).
    """

    entrypoint_name = 'Data.PredictorModelArrayConverter'
    inputs = {}
    outputs = {}

    if model is not None:
        inputs['Model'] = try_set(
            obj=model,
            none_acceptable=False,
            is_of_type=list)
    if output_model is not None:
        outputs['OutputModel'] = try_set(
            obj=output_model,
            none_acceptable=False,
            is_of_type=list)

    input_variables = {
        x for x in unlist(inputs.values())
        if isinstance(x, str) and x.startswith("$")}
    output_variables = {
        x for x in unlist(outputs.values())
        if isinstance(x, str) and x.startswith("$")}

    entrypoint = EntryPoint(
        name=entrypoint_name, inputs=inputs, outputs=outputs,
        input_variables=input_variables,
        output_variables=output_variables)
    return entrypoint
