# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
Models.Schema
"""


from ..utils.entrypoints import EntryPoint
from ..utils.utils import try_set, unlist


def models_schema(
        model,
        schema=None,
        **params):
    """
    **Description**
        Retrieve output model schema

    :param model: The transform model. (inputs).
    :param schema: The model schema (outputs).
    """

    entrypoint_name = 'Models.Schema'
    inputs = {}
    outputs = {}

    if model is not None:
        inputs['Model'] = try_set(
            obj=model,
            none_acceptable=False,
            is_of_type=str)
    if schema is not None:
        outputs['Schema'] = try_set(
            obj=schema,
            none_acceptable=False,
            is_of_type=str)

    input_variables = {
        x for x in unlist(inputs.values())
        if isinstance(x, str) and x.startswith("$")}
    output_variables = {
        x for x in unlist(outputs.values())
        if isinstance(x, str) and x.startswith("$")}

    entrypoint = EntryPoint(
        name=entrypoint_name, inputs=inputs, outputs=outputs,
        input_variables=input_variables,
        output_variables=output_variables)
    return entrypoint
