# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------------------------
# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
IidSpikeDetector
"""

__all__ = ["IidSpikeDetector"]


from ...entrypoints.timeseriesprocessingentrypoints_iidspikedetector import \
    timeseriesprocessingentrypoints_iidspikedetector
from ...utils.utils import trace
from ..base_pipeline_item import BasePipelineItem, DefaultSignature


class IidSpikeDetector(BasePipelineItem, DefaultSignature):
    """

    This transform detects the spikes in a i.i.d. sequence using adaptive
    kernel density estimation.

    .. remarks::
        ``IIDSpikeDetector`` assumes a sequence of data points that are
        independently sampled from one stationary
        distribution. `Adaptive kernel density estimation
        <https://en.wikipedia.org/wiki/Variable_kernel_density_estimation>`_
        is used to model the distribution.
        The `p-value <https://en.wikipedia.org/wiki/P-value`_> score
        indicates the likelihood of the current observation according to
        the estimated distribution. The lower its value, the more likely the
        current point is an outlier.

    :param confidence: The confidence for spike detection in the range [0,
        100].

    :param side: The argument that determines whether to detect positive or
        negative anomalies, or both. Available options are {``Positive``,
        ``Negative``, ``TwoSided``}.

    :param pvalue_history_length: The size of the sliding window for computing
        the p-value.

    :param params: Additional arguments sent to compute engine.

    .. seealso::
        :py:func:`IIDChangePointDetector
        <nimbusml.preprocessing.timeseries.IIDChangePointDetector>`,
        :py:func:`SsaSpikeDetector
        <nimbusml.preprocessing.timeseries.SsaSpikeDetector>`,
        :py:func:`SsaChangePointDetector
        <nimbusml.preprocessing.timeseries.SsaChangePointDetector>`.

    .. index:: models, timeseries, transform

    Example:
       .. literalinclude:: /../nimbusml/examples/IidSpikePointDetector.py
              :language: python
    """

    @trace
    def __init__(
            self,
            confidence=99.0,
            side='TwoSided',
            pvalue_history_length=100,
            **params):
        BasePipelineItem.__init__(
            self, type='transform', **params)

        self.confidence = confidence
        self.side = side
        self.pvalue_history_length = pvalue_history_length

    @property
    def _entrypoint(self):
        return timeseriesprocessingentrypoints_iidspikedetector

    @trace
    def _get_node(self, **all_args):
        algo_args = dict(
            source=self.source,
            name=self._name_or_source,
            confidence=self.confidence,
            side=self.side,
            pvalue_history_length=self.pvalue_history_length)

        all_args.update(algo_args)
        return self._entrypoint(**all_args)

    def partial_fit_transform(self, X, y=None, as_binary_data_stream=False,
                      **params):
        """
        Updateds fitted transform and applies it to data.

        :param X: array-like with shape=[n_samples, n_features] or else
        :py:class:`nimbusml.FileDataStream`
        :param y: array-like with shape=[n_samples]
        :return: pandas.DataFrame
        """
        if not hasattr(self, "model_") or self.model_ is None:
            return fit_transform(X, y, params)
        
        # Do not move these imports or the module fails
        # due to circular references.
        from ..entrypoints.timeSeries_onlineLearning import timeSeries_onlineLearning
        from .entrypoints import Graph

        online_node = timeSeries_onlineLearning(model_path=self.mmodel_, data='$data', output_data='$output_data')
        graph_nodes = [online_node]
        graph = Graph(
            dict(data=''), 
            dict(output_data=''), 
            False,
           *(graph_nodes))
        (out_model, out_data, out_metrics) = graph.run(verbose=True, X=self)
        return out_data

    def partial_fit(self, X, y=None, **params):
        """
        Updates fitted transform.

        :param X: array-like with shape=[n_samples, n_features] or else
        :py:class:`nimbusml.FileDataStream`
        :param y: array-like with shape=[n_samples]
        :return: self
        """
        if not hasattr(self, "model_") or self.model_ is None:
            return fit(X, y, params)

        # Do not move these imports or the module fails
        # due to circular references.
        from ..entrypoints.timeSeries_onlineLearning import timeSeries_onlineLearning
        from .entrypoints import Graph

        online_node = timeSeries_onlineLearning(model_path=self.mmodel_, data='$data', output_data='$output_data')
        graph_nodes = [online_node]
        graph = Graph(
            dict(data=''), 
            dict(output_data=''), 
            False,
           *(graph_nodes))
        (out_model, out_data, out_metrics) = graph.run(verbose=True, X=self)
        return self
