# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------------------------
# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
ClassifierVoting
"""

__all__ = ["ClassifierVoting"]


from ....utils.entrypoints import Component
from ....utils.utils import trace


class ClassifierVoting(Component):
    """
    **Description**
        Computes the fraction of positive predictions for each class from all the trained models, and outputs the class with the largest number

    :param params: Additional arguments sent to compute engine.

    """

    @trace
    def __init__(
            self,
            **params):

        self.kind = 'EnsembleMulticlassOutputCombiner'
        self.name = 'MultiVoting'
        self.settings = {}

        super(
            ClassifierVoting,
            self).__init__(
            name=self.name,
            settings=self.settings,
            kind=self.kind)
