# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------------------------
# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
ClassifierVoting
"""

__all__ = ["ClassifierVoting"]


from ...internal.core.ensemble.output_combiner.classifiervoting import \
    ClassifierVoting as core
from ...internal.utils.utils import trace


class ClassifierVoting(core):
    """
    **Description**
        Computes the fraction of positive predictions for each class from all the trained models, and outputs the class with the largest number

    :param params: Additional arguments sent to compute engine.

    """

    @trace
    def __init__(
            self,
            **params):
        core.__init__(
            self,
            **params)

    def get_params(self, deep=False):
        """
        Get the parameters for this operator.
        """
        return core.get_params(self)
